# Generated by Django 5.0 on 2023-12-15 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnounceImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('img', models.ImageField(upload_to='announceimg', verbose_name='宣传图文件')),
                ('aid', models.BigIntegerField(verbose_name='跳转文章ID')),
            ],
            options={
                'verbose_name': '宣传图管理',
                'verbose_name_plural': '宣传图管理',
            },
        ),
        migrations.CreateModel(
            name='RotationImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='轮播图名称')),
                ('img', models.ImageField(upload_to='rotationimg', verbose_name='图片文件')),
            ],
            options={
                'verbose_name': '轮播图管理',
                'verbose_name_plural': '轮播图管理',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='名称')),
            ],
            options={
                'verbose_name': '类型管理',
                'verbose_name_plural': '类型管理',
            },
        ),
        migrations.CreateModel(
            name='ViewIp',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('user_ip', models.CharField(max_length=15)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '访客统计',
                'verbose_name_plural': '访客统计',
            },
        ),
        migrations.CreateModel(
            name='WebsiteViews',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('views', models.IntegerField()),
            ],
            options={
                'verbose_name': '访问量统计',
                'verbose_name_plural': '访问量统计',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='文章标题')),
                ('content', models.FileField(upload_to='data', verbose_name='正文文件')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tjweb.type', verbose_name='所属类型')),
            ],
            options={
                'verbose_name': '文章管理',
                'verbose_name_plural': '文章管理',
            },
        ),
    ]
