# Generated by Django 5.0 on 2023-12-18 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tjweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotationimg',
            name='aid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tjweb.article', verbose_name='跳转文章ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announceimg',
            name='aid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tjweb.article', verbose_name='跳转文章ID'),
        ),
    ]
