# Generated by Django 5.0 on 2023-12-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tjweb', '0002_rotationimg_aid_alter_announceimg_aid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='link_logo', verbose_name='友链Logo')),
                ('title', models.CharField(max_length=128, verbose_name='显示内容')),
                ('url', models.URLField(blank=True, max_length=256, verbose_name='跳转地址')),
            ],
            options={
                'verbose_name': '友链管理',
                'verbose_name_plural': '友链管理',
            },
        ),
    ]
