# Generated by Django 5.0 on 2023-12-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tjweb', '0003_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='belong',
            field=models.SmallIntegerField(choices=[(1, '通知公告'), (2, '工作动态'), (3, '部门动态'), (4, '专题活动')], verbose_name='所属类型'),
        ),
    ]
